efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file

defaultFileSystemType: "ext4"

availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]

initialPartitioningChoice: erase
initialSwapChoice: file

enableLuksAutomatedPartitioning: true

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
