dontChroot: false
timeout: 1800

script:
    - command: 'sh -c "if grep -qs 0x10de /sys/bus/pci/devices/*/vendor; then apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-driver linux-headers-amd64; fi; exit 0"'