defaultGroups:
    - users
    - sudo
    - lp
    - video
    - audio
    - storage
    - cdrom
    - dip
    - plugdev
    - lpadmin

hostname:
    location: EtcFile
    writeHostsFile: true
    template: "prototype"
    forbidden: [ localhost ]

autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: true
doReusePassword: false
passwordRequirements:
    minLength: 4

allowWeakPasswords: true
allowWeakPasswordsDefault: true
