showSupportUrl:         false
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    7.5
    requiredRam:        2.0
    internetCheckUrl:   http://www.google.com
    check:
        - storage
        - ram
        - power
    required:
        - storage
        - ram
        - power
